### ISSUE TITLE
how to set width is 100%?

### ISSUE THREAD

**Issue by MJRT** [flixyudh/rn-flix#1]

**Comment by flixyudh** [comment]
Hi @MJRT , currently I don't have any plan to support percentage `width` or `height` props, but you can use `style` props to achieve what you want as it is pass the style to `Image` props directly

example

```js
<AutoImage source={source} style={{ width: '100%', height: '50%' }} />
```

result:

https://github.com/user-attachments/assets/8ec80ba8-e389-417e-a39f-5884ddacb9bc
